sudo: required
services:
  - docker

before_install:
  - docker build -t istrupin/docker-compose-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true istrupin/docker-compose-demo npm run test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
  verbose: true
  skip_cleanup: true