sudo: required
services:
  - docker

before_install:
  - docker build -t istrupin/docker-compose-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true istrupin/docker-compose-demo npm run test

deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: $AZURE_WA_SITE
  verbose: true
  skip_cleanup: true